# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="muse"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git ruby autojump brew rbenv bundler)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=~/.rbenv/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:~/.bin:/usr/X11/bin
export EDITOR=vim

# Enable Shims and autocompletion for rbenv
eval "$(rbenv init -)"

# Disable auto correct
unsetopt correct_all

# Perfoce shit
export P4CLIENT=cdickerson
export P4USER=cdickerson
export P4PORT=perflax01:1666
export P4CHARSET=utf8

# Use mvim -v for vim
#alias vim="mvim -v"
#alias vi="mvim -v"

# Vim as man pager
export MANPAGER="col -b | vim -c 'set ft=man ts=8 nomod nolist nonu noma' -"

# source-highlight
export LESSOPEN="| /usr/local/Cellar/source-highlight/3.1.5/bin/src-hilite-lesspipe.sh %s"
export LESS=' -R '

# Source euca shit
#source ~/.euca/euca-kniferc

# Alai
alias vd='vagrant destroy --force'
alias vu='vagrant up'
alias vp='vagrant provision'
alias vssh='vagrant ssh'
alias more='less'
alias knifep='knife \$\@ -c ~/chef-auth/chef.lax1.pivotal.knife.rb'
